steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-world-kube:$SHORT_SHA'
      - '.'
      
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hello-world-kube:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    id: 'Deploy'
    args:
      - 'run'
      - '--filename=k8s/'
      - '--image=gcr.io/$PROJECT_ID/hello-word-kube:$SHORT_SHA'
      - '--location=us-east1-c'
      - '--cluster=prv-compradecarteiras'
