steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hello-world-kube:$SHORT_SHA'
      - '.'
      
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hello-world-kube:$SHORT_SHA'
# Deploy image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    args:
      - 'run'
      - 'deploy'
      - 'compra-de-carteiras-tralci'
      - '--image'
      - 'gcr.io/prv-compradecarteiras/hello-world-kube:$COMMIT_SHA'
      - '--region'
      - 'us-east1-c'
      - '--platform'
      - 'gke'
      - '--cluster'
      - 'prv-compradecarteiras'
      - '--cluster-location'
      - 'us-east1-c'
images:
  - gcr.io/prv-compradecarteiras/hello-world-kube
