apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-carteira
spec:
  selector:
    matchLabels:
      app: compra-carteira
  template:
    metadata:
      labels:
        app: compra-carteira
    spec:
      containers:
        - name: compra-carteira
          image: docker pull gcr.io/prv-compradecarteiras/hello-word-kube:latest
          envFrom:             
          - secretRef:                
              name: compra-carteira-env
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
