version: '1.0'
stages:
  - build
  - test
steps:
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: tralci/hello-world-kube-dev
    working_directory: ./
    tag: '${{CF_BRANCH}}-${{CF_SHORT_REVISION}}'
    dockerfile: ./Dockerfile
    stage: build
    when:
      condition:
        all:
          CheckCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "check ci") == true'
  UnitTests:
    image: '${{BuildingDockerImage}}' # image that contains installed tools for performing test commands
    stage: test
    commands:
      - echo $(date)
    on_success:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: true
    on_fail:
      metadata:
        set:
          - '${{BuildingDockerImage.imageId}}':
              - CF_QUALITY: false
