version: '1.0'
stages:
  - build
  - deploy
steps:
  BuildDockerImage:
    title: Building Docker Image
    type: build
    image_name: tralci/hellowordkube
    working_directory: ./
    tag: 'dev-${{CF_SHORT_REVISION}}'
    dockerfile: ./Dockerfile
    stage: build
    when:
      branch:
        only:
          - /^dev-*/i
  Push_CF_image:
    type: parallel
    steps:
      push_to_codefresh:
        title: Pushing to Docker Registry
        type: push
        candidate: '${{BuildDockerImage}}'
        tag: 'dev-${{CF_SHORT_REVISION}}'
        registry: cfcr
    stage: build
  DeployApp:
    image: codefresh/cf-deploy-kubernetes
    tag: latest
    working_directory: ${{main_clone}}
    stage: deploy
    commands:
      - /cf-deploy-kubernetes ./codefresh/deployment-dev.yml
    environment:
      - KUBECONTEXT=iugu-dev@iugu-dev
      - KUBERNETES_NAMESPACE=default
      - KUBERNETES_DEPLOYMENT_TIMEOUT=600
