kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-word-kube-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-word-kube-prod
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-word-kube-prod
    spec:
      containers:
        - name: hello-word-kube-prod
          image: 'r.cfcr.io/iugu/tralci/hellowordkube:production-{{CF_SHORT_REVISION}}'
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 40m
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: codefresh-generated-r.cfcr.io-cfcr-default
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
