kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-word-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-word-kube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-word-kube
    spec:
      containers:
        - name: ahello-word-kube
          image: 'r.cfcr.io/tralci/tralci/hellowordkube:production-{{CF_SHORT_REVISION}}'
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: codefresh-generated-r.cfcr.io-cfcr-default
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
